### ISSUE TITLE
여행삭제 Alert 버튼 텍스트 색깔

### ISSUE THREAD

**Issue by nalaworld** [boostcamp-2020/Project18-A-BoostPocket#112]
### 의논하고 싶은 주제
애플 디폴트에서는 삭제할때 오히려 취소가 파랑, 삭제버튼이 빨강색이네요! 이 가이드라인대로 변경하는건 어떨까요!?

![스크린샷 2020-12-02 오전 2 13 37](https://user-images.githubusercontent.com/35067611/100773311-09193700-3444-11eb-8054-2e98e06c9faf.png)
![스크린샷 2020-12-02 오전 1 52 21](https://user-images.githubusercontent.com/35067611/100773313-0a4a6400-3444-11eb-9b97-bc72974461d8.png)

**Comment by songjucho** [comment]
<img src="https://user-images.githubusercontent.com/65107199/100816139-cf1e5400-3488-11eb-9a43-f0b7e4e16a71.png" width=200>
😇
