### ISSUE TITLE
여행 목록 화면 셀 부분 애니메이션 적용 실패

### ISSUE THREAD

**Issue by songjucho** [boostcamp-2020/Project18-A-BoostPocket#74]
### Summary  
- 여행이 3개 이상일 때, 레이아웃을 바꾸면 위의 두개 셀을 제외한 셀의 애니메이션이 적용이 안됩니다..
해결할 수 있는 문제인지 모르겠어요...

![issue](https://user-images.githubusercontent.com/65107199/100450735-84ec4a00-30f9-11eb-84dd-8438e69b7abb.gif)

**Comment by songjucho** [comment]
applySnapshot 메소드 내부 snapshot.apply()의 completion을 정하지 않으면 해결됨... 하지만 datasource 를 다시 configure하지 않아서 셀 자체를 바꾸는 것은 조금 더 고민이 필요합니다. 강제로 configureDataSource를 호출한다던가..?

<br>

```swift
// 고치기 전
self.dataSource.apply(snapShot, animatingDifferences: true) {
    self.travelListCollectionView.reloadData()
}

// 고친 후
dataSource.apply(snapShot, animatingDifferences: true)
```

> 근데 저희 reload를 내부에서 한 이유가 뭐였죠...? 기억이 안납니다 ㅋㅅㅋㅅ
@sihyungyou @devilzCough

**Comment by nalaworld** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 너무고생하샼ㅅ어요! 저희 그 여행한 나라 개수가 바로업데이트가 안돼서 리로드 추가했던거로 기억해요 ㅎㅎ

**Comment by songjucho** [comment]
Aㅏ.... 맞네요........ 저거 근뎈ㅋㅋㅋ 그러면 버그가 생긴 이유만 알아내고 문제 해결은 안된거네요...^^...... 흑흑...^^^^^^^

**Comment by devilzCough** [comment]
마자용 animatingDifferences true 하면 데이터가 reload 되지 않아서 해준거였습니다. 근데 무슨 문제인건지 잘 모르겠어요 ㅋㅋ 애니메이션 적용이 어떤게 안되는건지???
